package com.ty.mapper;

import com.ty.entity.TestTy;

import java.util.List;

public interface TestTyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    int insert(TestTy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    int insertSelective(TestTy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    TestTy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    int updateByPrimaryKeySelective(TestTy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    int updateByPrimaryKey(TestTy record);

    List<TestTy> selectList();
}