package com.ty.mapper;

import com.ty.entity.UserEntity;

public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    UserEntity selectByPrimaryKey(Integer id);

    /**
     * 通过用户名查询用户信息
     * @param username
     * @return
     */
    UserEntity selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    int updateByPrimaryKey(UserEntity record);
}