package com.ty.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test-ty
 *
 * @mbg.generated do_not_delete_during_merge Mon May 06 16:19:17 CST 2019
 */
public class TestTy implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test-ty.id
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test-ty.lakers_name
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    private Date lakersName;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test-ty.quantity
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    private Long quantity;

    /**
     * Database Column Remarks:
     *   序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test-ty.sequence_number
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    private String sequenceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test-ty.lakers_loc
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    private String lakersLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test-ty
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test-ty.id
     *
     * @return the value of test-ty.id
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test-ty.id
     *
     * @param id the value for test-ty.id
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test-ty.lakers_name
     *
     * @return the value of test-ty.lakers_name
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public Date getLakersName() {
        return lakersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test-ty.lakers_name
     *
     * @param lakersName the value for test-ty.lakers_name
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public void setLakersName(Date lakersName) {
        this.lakersName = lakersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test-ty.quantity
     *
     * @return the value of test-ty.quantity
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test-ty.quantity
     *
     * @param quantity the value for test-ty.quantity
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test-ty.sequence_number
     *
     * @return the value of test-ty.sequence_number
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test-ty.sequence_number
     *
     * @param sequenceNumber the value for test-ty.sequence_number
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public void setSequenceNumber(String sequenceNumber) {
        this.sequenceNumber = sequenceNumber == null ? null : sequenceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test-ty.lakers_loc
     *
     * @return the value of test-ty.lakers_loc
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public String getLakersLoc() {
        return lakersLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test-ty.lakers_loc
     *
     * @param lakersLoc the value for test-ty.lakers_loc
     *
     * @mbg.generated Mon May 06 16:19:17 CST 2019
     */
    public void setLakersLoc(String lakersLoc) {
        this.lakersLoc = lakersLoc == null ? null : lakersLoc.trim();
    }
}