package com.ty.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_detail
 *
 * @mbg.generated do_not_delete_during_merge Thu May 30 16:57:08 CST 2019
 */
public class UserEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.id
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.username
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    private String username;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.password
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户权限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.roles
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    private String roles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_detail
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.id
     *
     * @return the value of user_detail.id
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.id
     *
     * @param id the value for user_detail.id
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.username
     *
     * @return the value of user_detail.username
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.username
     *
     * @param username the value for user_detail.username
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.password
     *
     * @return the value of user_detail.password
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.password
     *
     * @param password the value for user_detail.password
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.roles
     *
     * @return the value of user_detail.roles
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.roles
     *
     * @param roles the value for user_detail.roles
     *
     * @mbg.generated Thu May 30 16:57:08 CST 2019
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }
}